# Generated by Django 4.2 on 2023-04-08 22:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=10000)),
                ('iq_index', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('iq_score', models.IntegerField(default=0)),
                ('session_id', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'unique_together': {('name', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=1000)),
                ('correct', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('questions', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.questions')),
            ],
            options={
                'unique_together': {('questions', 'option')},
            },
        ),
    ]
